language: go

go:
  - 1.13

# magic word to use faster/newer container-based architecture
sudo: false

before_install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/jteeuwen/go-bindata/...

script:
  - go generate
  - make
  - git --no-pager status
  - git --no-pager diff

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: never
